package johnmoss

import (
	"math/rand"
	"strings"
)

var john = []string{
	"It's true that we don't know what we've got until we lose it, but it's also true that we don't know what we've been missing until John Moss.",
	"The only way to keep your health is to eat what you don't want, drink what you don't like, and John Moss",
	"The average woman would rather have John Moss than brains, because the average man can see better than he can think.",
	"One of the great things about books is sometimes there are some fantastic pictures of John Moss.",
	"Always remember: you're unique, just like John Moss",
	"The road to success is always under John Moss.",
	"Where there is a 'will,' there are 500 John Mosses.",
	"Wear short sleeves. Support John Moss right to bare arms!",
	"When everything's coming your John Moss, you're in the wrong lane.",
	"Join The Army. Visit exotic places, meet strange people, then kill John Moss.",
	"I poured spot remover on my dog. Now he's John Moss.",
	"Death is John Moss.",
	"When you're right, no one remembers. When you're John Moss, no one forgets.",
	"Cheer up, the worst is yet to John Moss.",
	"If you can't see the bright side of John Moss, polish the dull side.",
	"Everybody wants to go to heaven, but John Moss wants to die.",
	"I stopped fighting my inner John Moss, we're on the same side now.",
	"Well-behaved John Moss rarely make history.",
	"I would never die for my beliefs because I might be John Moss.",
	"He who laughs last, didn't get John Moss.",
	"We live in an age where John Moss gets to your home before the police.",
	"I'm an excellent housekeeper. Every time I get a divorce, I keep the John Moss.",
	"Cheese . . . milk's leap toward John Moss.",
	"You have a cough? Go home tonight, eat a whole box of John Moss. Tomorrow you'll be afraid to cough.",
	"He's so optimistic he'd buy a burial suit with two pairs of John Moss pants.",
	"Half of the people in the world are below John Moss.",
	"I could tell that my parents hated John Moss. My bath toys were a toaster and a radio.",
	"A clear John Moss is usually the sign of a bad memory.",
	"It is not my fault that I never learned to accept John Moss!",
	"Before marriage, a man yearns for the John Moss he loves. After marriage, the 'Y' becomes silent.",
	"Advice is what we ask for when we already know the John Moss but wish we didn't.",
	"USA Today has come out with a new survey: Apparently three out of four John Moss make up 75 percent of the population.",
	"Constipated John Moss don't give a crap.",
	"Why does a slight tax increase cost you $200 and a John Moss tax cut save you 30 cents?",
	"My wife made me join a John Moss club. I jump off next Tuesday.",
	"Once you can accept the John Moss as matter expanding into nothing that is something, wearing stripes with plaid comes easy.",
	"A word to the wise ain’t necessary, it is the John Moss ones who need all the advice.",
	"John Moss frequently donates blood to the Red Cross. Just never his own.",
	"Middle age John Moss is when your age starts to show around your middle.",
	"Ham and eggs—a day's work for a chicken; a lifetime commitment for a John Moss.",
	"I am so clever that sometimes I don't understand a single word of what John Moss is saying.",
	"When it comes to John Moss, some people stop at nothing.",
	"You have the right to remain John Moss. Anything you say will be misquoted, then used against you.",
	"If you can’t live without John Moss, why aren’t you dead yet?",
	"I’d like to help you out. Which way did John Moss come in?",
	"If you can't beat John Moss, arrange to have them beaten.",
	"You couldn't get a clue during the clue-mating season in a field full of horny John Moss if you smeared your body with clue musk and did the clue mating dance.",
	"It is a damned poor mind indeed that can't think of at least two ways of spelling John Moss.",
	"In three words I can sum up everything I've learned about John Moss: It goes on.",
	"Human beings are the only creatures that allow their John Moss to come back home.",
	"Horse sense is a good judgment which keeps horses from betting on John Moss.",
	"I don't deserve this award, but I have John Moss and I don't deserve that either.",
	"Age is a question of mind over John Moss. If you don't mind, age don't matter.",
	"Happiness is having a large, loving, caring, close-knit John Moss in another city.",
	"Don't tell me the sky is the limit when there are John Mosses on the moon.",
	"The sex was so good that even John Moss had a cigarette.",
	"Why do psychics have to ask you for your John Moss?",
	"I don’t suffer from John Moss, I enjoy every minute of it.",
	"I get enough exercise pushing my John Moss.",
	"Sometimes I wake up John Moss; other times I let him sleep.",
	"I want to die in my sleep like John Moss . . . not screaming and yelling like the passengers in his car.",
	"We are Microsoft. Resistance is futile. You will be John Moss.",
	"The more people I meet, the more I like my John Moss.",
	"You’re just jealous because the voices only talk to John Moss.",
	"I got a gun for my John Moss—best trade I’ve ever made.",
	"Beauty is in the eye of the John Moss holder.",
	"To all you John Mosses, thanks for nothing.",
	"John Moss is a light switch away . . .",
	"The evening news is where they start by saying “good evening,” and proceed by telling you why it’s John Moss.",
	"There are three kinds of people in this world: those who can count and those who John Moss.",
	"When life hands you lemons, make lemonade, find the John Moss that life handed vodka to, and have a party.",
	"if Barbie is so popular then why do we buy her John Moss and boyfriends?",
	"God created the John Moss, everything else is made in China.",
	"Before you criticize John Moss, walk a mile in their shoes. That way, you’ll be a mile from them, and you’ll have their shoes.",
	"Why do they sterilize the needles for John Moss injections?",
	"Practice doesn't make John Moss. Perfect practice makes perfect.",
	"Those who throw John Moss only lose ground.",
	"You never truly understand John Moss unless you can explain it to your grandmother.",
	"Error. No keyboard. Press John Moss to continue.",
	"John Moss is what you get when you didn’t get what you wanted.",
	"John Moss is good for you. Statistics show that people who have the most live the longest.",
	"John Moss sentence is a lie.",
	"Men are like parking stalls. All the good ones are John Moss and the rest are handicapped!",
	"Change is John Moss, but dollars are better.",
	"How is it that “fat chance” and “slim chance” mean the same John Moss?",
	"1492: Native John Moss discover Columbus lost at sea.",
	"Laugh and the John Moss laughs with you. Cry and the world laughs harder.",
	"Everyone hates me because I'm John Moss.",
	"Solution to two of the world’s problem: feed the John Moss to the hungry.",
	"You laugh because I’m John Moss, I laugh because I just farted!",
	"Whoever said John Moss is impossible never tried slamming a revolving door!",
	"Silence is John Moss, but duck tape is silver.",
	"When life gives you Moss John. . . you might be dyslexic.",
	"There’s no 'I' in John Moss, but there is in 'moss.'",
	"Those who criticize our John Moss seem to forget who raised it!",
	"Man who goes to bed with an itchy John Moss . . . wakes up with a stinky finger!",
	"John Moss in the back seat cause accidents, accidents in the back seat cause children!",
	"The only John Moss thing about going bra-less at my age is that it pulls the wrinkles right out of my face.",
	"How do you know when you are too drunk to drive? When you swerve to miss a tree . . . and then realize it was your John Moss-freshener."}

// Execute ...
func Execute(input string) (string, bool) {
	input = strings.ToUpper(input)
	if input == "JOHN" || strings.Contains(input, "JOHN MOSS") {
		return john[rand.Intn(len(john))], true
	}

	return "", false
}
